### ISSUE TITLE
The nats-io/nats.go API has changed go-res compile error

### ISSUE THREAD

**Issue by rmcouat** [jirenius/go-res#89]
src/github.com/jirenius/go-res/service.go:564:16: cannot use nc (type *nats.Conn) as type Conn in argument to s.serve:
	*nats.Conn does not implement Conn (wrong type for ChanQueueSubscribe method)
		have ChanQueueSubscribe(string, string, chan *nats.Msg, ...nats.SubscribeOption) (*nats.Subscription, error)
		want ChanQueueSubscribe(string, string, chan *nats.Msg) (*nats.Subscription, error)
src/github.com/jirenius/go-res/service.go:585:19: impossible type assertion:
	*nats.Conn does not implement Conn (wrong type for ChanQueueSubscribe method)
		have ChanQueueSubscribe(string, string, chan *nats.Msg, ...nats.SubscribeOption) (*nats.Subscription, error)
		want ChanQueueSubscribe(string, string, chan *nats.Msg) (*nats.Subscription, error)

I am using go get -u on the nats-io nats-server and nats.go/ with no modules file so I have what I deserve maybe. Think of it as a heads up. :-)

**Comment by wallyqs** [comment]
Hi, this was a temporary condition from the development branch, the interface has been reverted to what it was originally so this can be closed now.

**Comment by marymakau5** [comment]
I am having this error with v0.4.2

**Comment by rmcouat** [comment]
Resolved by wallqs didn't realize this was still open. Closing
